name: Dev env promo build and deploy

on:
  push:
    branches:
      - bau-setup-repo
      - main
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    environment: dev
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Upload to ECR and tag
        uses: govuk-one-login/devplatform-upload-action-ecr-codebuild-image@bau-remove-sam
        with:
          role-to-assume-arn: ${{ secrets.ROLE_TO_ASSUME }}
          container-sign-kms-key-arn: ${{ secrets.CONTAINER_SIGN_KMS_KEY }}
          working-directory: image
          ecr-repo-name: ${{ secrets.PROMOTION_ECR_REPO }}
          dockerfile: DockerfilePromotion
